apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first. This is a distribution generated for learning and experimenting
  annotations:
    github.com/project-slug: on-clouds/backstage 
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: platform-team
  lifecycle: experimental
